<?php
/**
 * @file
 * Provides primary Drupal hook implementations.
 *
 * @author Heshan Wanigasooriya ("heshan.lk", http://drupal.org/user/199102)
 * @author Jimmy Berry ("boombatower", http://drupal.org/user/214218)
 */

/**
 * Implements hook_menu().
 */
function amazon_fps_ui_menu() {
  $items = array();

  $items['admin/settings/amazon_fps'] = array(
    'title' => 'Amazon FPS library for PHP',
    'description' => 'Configure Amazon FPS library settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('amazon_fps_ui_settings_form'),
    'access arguments' => array('access administration pages'),
  );

  return $items;
}

/**
 * Settings form.
 */
function amazon_fps_ui_settings_form(&$form_state) {
  $form['aws_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Amazon Web Services Key'),
    '#default_value' => variable_get('aws_key', ''),
    '#required' => TRUE,
    '#description' => t('Amazon Web Services Key. Found in the AWS Security Credentials. You can also pass this value as the first parameter to a service constructor.'),
  );
  $form['aws_secret_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Amazon Web Services Secret Key'),
    '#default_value' => variable_get('aws_secret_key', ''),
    '#required' => TRUE,
    '#description' => t('Amazon Web Services Secret Key. Found in the AWS Security Credentials. You can also pass this value as the second parameter to a service constructor.'),
  );
  return system_settings_form($form);
}

